package sg.gov.tech.gds_swe_challenge.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;

import java.util.List;

@Schema(description = "Invite user to session request")
public record InviteUserRequest(
        @Schema(description = "Session unique identifier generated by backend", example = "1")
        long sessionId,
        @Schema(description = "List of usernames to invite to session", example = "[\"chinpui\", \"alice\"]")
        @NotEmpty(message = "At least one username required")
        List<String> usernames
) {}