package sg.gov.tech.gds_swe_challenge.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import sg.gov.tech.gds_swe_challenge.constant.AppConstants;

@Schema(description = "Restaurant submission request")
public record SubmitRestaurantRequest(
        @Schema(description = "Restaurant name", example = "Kopitiam")
        @NotBlank String name,
        @Schema(description = "Session unique identifier generated by backend", example = "1")
        long sessionId,
        @Schema(description = "Session name", example = "team-alpha")
        String sessionName
) {
    @JsonCreator
    public SubmitRestaurantRequest(
            @JsonProperty("name") @NotBlank String name,
            @JsonProperty("sessionId") Long sessionId,
            @JsonProperty("sessionName") String sessionName) {
        this(name,
                sessionId != null ? sessionId : AppConstants.GLOBAL_SESSION_ID,
                sessionName != null ? sessionName : AppConstants.GLOBAL_SESSION_NAME);
    }

    public SubmitRestaurantRequest(@NotBlank String name) {
        this(name, AppConstants.GLOBAL_SESSION_ID, AppConstants.GLOBAL_SESSION_NAME);
    }
}
